### ISSUE TITLE
CrAs T MRL3 Editor populating the library issue

### ISSUE THREAD

**Issue by Moonklu** [Ezekial711/MonsterHunterWorldModding#1]
This was asked by Asterisk to be fixed later.
I opened an mrl3 file to edit, try to populate the library from the compendium.
The program crashed when I dragged the most top level material (e.g. VFX_Water_Mt__2)
into the library instead of dragging one of the files in the list of that material.
Asterisk said the program should just block it from happening instead of crashing.
![image](https://user-images.githubusercontent.com/59110411/71305322-d5eeac80-2386-11ea-8a1a-8b0c5a429bac.png)

**Comment by AsteriskAmpersand** [comment]
Wrong tool location. I'll move it to the correct repo.
