### ISSUE TITLE
Not working anymore with Iceborn Addon

### ISSUE THREAD

**Issue by vinochino** [Ezekial711/MonsterHunterWorldModding#2]
So as the release of Iceborn on January 9th, every Mod and Save Editor isnt working anymore because of the following changes to the Game:

EVERY SINGLE MOD YOU HAVE INSTALLED IS BROKEN
-Save Editor - Capcom changed save structure and added encryption: ETA - End of Month maybe
-Chunk Tool - Capcom encrypts the chunks now, we have the keys but not the order. We are working on it: ETA - Hopefully before end of next week
-Literally Everything Else - Models, Effects, Item Shop, etc - Capcom changed all formats, requires the Chunk to reverse engineer again

Is this Editor going to be updated to Iceborns new System? It was the best editor there is so it would be really nice 😁

**Comment by AsteriskAmpersand** [comment]
This isn't an editor. All of this have been addressed.
