### ISSUE TITLE
What about ID of Rajang Weapons?

### ISSUE THREAD

**Issue by Ahhhuang** [Ezekial711/MonsterHunterWorldModding#3]
It seems like the list doesn't include Rajang Weapon. Do I have any other ways to have Rajang weapons' id? (BTW, I'm looking for Rajang Heavy Bowgun: Rajang Destroyer). Thanks.

**Comment by MAXofShanghai** [comment]
My weapon list are writen by Chinese so I'm not sure about this.


You may try:wp/hbg/bs_hbg022, this one should be the Rajang Heavy Bowgun you looking for.


BTW:wp/lbg/bs_lbg003 is the Rajang Light Bowgun.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ahhhuang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 晚上11:14
收件人:&nbsp;"Ezekial711/MonsterHunterWorldModding"<MonsterHunterWorldModding@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ezekial711/MonsterHunterWorldModding] What about ID of Rajang Weapons? (#3)




It seems like the list doesn't include Rajang Weapon. Do I have any other ways to have Rajang weapons' id? (BTW, I'm looking for Rajang Heavy Bowgun: Rajang Destroyer). Thanks.

**Comment by neoanguiano** [comment]
20 and 21 in GS

**Comment by AquillaAzure** [comment]
It also doesnt look like it involves Raiging brachy, altho am just looking for chargeblade~

**Comment by AsteriskAmpersand** [comment]
Check the Weapon Dump entries:
https://github.com/Ezekial711/MonsterHunterWorldModding/wiki/Weapon-ID-Dump-(SA,-CB)
